// SPDX-License-Identifier: MIT
// Copyright (C) 2018-present iced project and contributors

// ⚠️This file was generated by GENERATOR!🦹‍♂️

#pragma once
#ifndef ICED_X86_INTERNAL_TABLES_HPP
#define ICED_X86_INTERNAL_TABLES_HPP

#include "iced_x86/mnemonic.hpp"
#include "iced_x86/memory_size.hpp"
#include "iced_x86/code.hpp"

#include <cstdint>

namespace iced_x86 {
namespace internal {

/// @brief Code to Mnemonic mapping table.
extern const Mnemonic g_code_to_mnemonic[4936];

/// @brief Instruction operand counts table.
extern const uint8_t g_instruction_op_counts[4936];

/// @brief Instruction memory sizes table.
extern const MemorySize g_instruction_memory_sizes[4936];

} // namespace internal
} // namespace iced_x86

#endif // ICED_X86_INTERNAL_TABLES_HPP
